server:
    port: 8081
management:
    security:
        enabled: false

spring:
    datasource:
        url: 'jdbc:mysql://localhost:3306/risk_management?characterEncoding=UTF-8'
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: create-drop